package com.sharaai.ukhane;


public interface AppConstants
{
	
	   
	public static final int ID1 = 0;
	public static final int ID2 = 1;
	public static final int ID3 = 2;
	public static final int ID4 = 3;
	public static final int ID5 = 4;
	public static final int ID6 = 5;
	public static final int ID7 = 6;
	public static final int ID8 = 7;
	public static final int ID9 = 8;
	public static final int ID10 = 9;
	public static final int ID11 = 10;
	

	public static final int [][] categoryUniqueId= {
		{ID1,ID1},
		{ID2,ID2},
		{ID3,ID3},
		{ID4,ID4},
		{ID5,ID5},
		{ID6,ID6},
		{ID7,ID7},
		{ID8,ID8},
		{ID9,ID9},
		{ID10,ID10},
	};
	public static final int [] categoryUniqueIdName= {
		R.string.f_cat_1,
		R.string.f_cat_2,
		R.string.f_cat_3,
		R.string.f_cat_4,
		R.string.f_cat_5,
		R.string.f_cat_6,
		R.string.f_cat_7,
		R.string.f_cat_8,
		R.string.f_cat_9,
		R.string.f_cat_10,
		
	};
	
	public static final int [] categoryIcon= {
		R.drawable.icon_lagnatil,
		R.drawable.icon_24x7,
		R.drawable.icon_gamtidar,
		R.drawable.icon_pujeche,
		R.drawable.icon_mangalgauri,
		R.drawable.icon_dohale,
		R.drawable.icon_barshache,
		R.drawable.icon_lagnaaadhiche,
		R.drawable.icon_grahpravesh,
		R.drawable.icon_sanwan,
		R.drawable.icon_sanwan,
	};
//	public static final int [][] categoryDetailImage= {
////		{R.drawable.funny_0,R.drawable.funny_1,R.drawable.funny_2,R.drawable.funny_3,R.drawable.funny_4},
////		{R.drawable.marriage_0,R.drawable.marriage_1,R.drawable.marriage_2,R.drawable.marriage_3,R.drawable.marriage_4},
////		{R.drawable.puja_0,R.drawable.puja_1,R.drawable.puja_2,R.drawable.puja_3,R.drawable.puja_4},
////		{R.drawable.home_0,R.drawable.home_1,R.drawable.home_2,R.drawable.home_3,R.drawable.home_4},
////		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
////		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
////		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
////		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
////		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
////		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
//		{}	
//	}; 
	
	public static final int [][] categoryDetailImage= {
		{
			R.drawable.cat_marriage1,R.drawable.cat_marriage2,R.drawable.cat_marriage3,R.drawable.cat_marriage4,R.drawable.cat_marriage5
		},

		{
			R.drawable.cat_24_1,R.drawable.cat_24_2,R.drawable.cat_24_3,R.drawable.cat_24_4,R.drawable.cat_24_5
		},
		{
			R.drawable.cat_gamti1,R.drawable.cat_gamti2,R.drawable.cat_gamti3,R.drawable.cat_gamti4,R.drawable.cat_gamti5
		},
		{
			R.drawable.cat_puja1,R.drawable.cat_puja2,R.drawable.cat_puja3,R.drawable.cat_puja4,R.drawable.cat_puja5
		},

		{
			R.drawable.cat_mangala1,R.drawable.cat_mangala2,R.drawable.cat_mangala3,R.drawable.cat_mangala4,R.drawable.cat_mangala5
		},
		{
			R.drawable.cat_dohale1,R.drawable.cat_dohale2,R.drawable.cat_dohale3,R.drawable.cat_dohale4,R.drawable.cat_dohale5
		},
		{
			R.drawable.cat_barshache1,R.drawable.cat_barshache2,R.drawable.cat_barshache3,R.drawable.cat_barshache4,R.drawable.cat_barshache5
		},
		{
			R.drawable.cat_lagnaadhi1,R.drawable.cat_lagnaadhi2,R.drawable.cat_lagnaadhi3,R.drawable.cat_lagnaadhi4,R.drawable.cat_lagnaadhi5
		},
		{
			R.drawable.cat_grah1,R.drawable.cat_grah2,R.drawable.cat_grah3,R.drawable.cat_grah4,R.drawable.cat_grah5
		},
		{
			R.drawable.cat_sanvar1,R.drawable.cat_sanvar2,R.drawable.cat_sanvar3,R.drawable.cat_sanvar4,R.drawable.cat_sanvar5,
		},
		//		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
		//		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
		//		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
		//		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
		//		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
		//		{R.drawable.festive_0,R.drawable.festive_1,R.drawable.festive_2,R.drawable.festive_3,R.drawable.festive_4},
		{}	
	};

//	public static final int [][] categoryDetailImageUser0= {
//		{
////			R.drawable.entry_7,
////			R.drawable.mangalsutr_4,
////			R.drawable.entry_3,
////			R.drawable.bride_3,
////			R.drawable.ram_1,
////			R.drawable.green_sadi_1,
////			R.drawable.fulvat,
////			R.drawable.rose_1,
////			R.drawable.varmala,
////			R.drawable.mehandi_2,
////			R.drawable.lunch_3,
////			R.drawable.garland_0,
////			R.drawable.entry_1,
////			R.drawable.green_bangle_1,
////			R.drawable.marriage_14,
////			R.drawable.marriage_10,
////			R.drawable.mangalsutr_4,
////			R.drawable.bride_3,
////			R.drawable.namskar_0,
////			R.drawable.mehandi_1,
////			R.drawable.entry_4,
////			R.drawable.diya_0,
////			R.drawable.mangalsutr_3,
////			R.drawable.entry_3,
////			R.drawable.sea_romance_3,
////			R.drawable.entry_1,
////			R.drawable.ganesh_4,
////			R.drawable.fire_1,
////			R.drawable.shankar,
////			R.drawable.sea_romance_4,
////			R.drawable.krishna_1,
////			R.drawable.kanyadan,
////			R.drawable.ram_0,
////			R.drawable.taj_0,
////			R.drawable.hand_hand_1,
////			R.drawable.marriage_3,
////			R.drawable.shreekhand_1,
////			R.drawable.child_1,
////			R.drawable.marriage_7,
////			R.drawable.rose_0,
////			R.drawable.marriage_13,
////			R.drawable.rangoli_0,
////			R.drawable.marriage_13,
////			R.drawable.shivaji_0,
////			R.drawable.entry_5,
////			R.drawable.bride_1,
////			R.drawable.marriage_0,
////			R.drawable.eye_1,
////			R.drawable.heart,
////			R.drawable.tirupati,
////			R.drawable.green_bangle_1,
////			R.drawable.halva_1,
////			R.drawable.lunch_0,
////			R.drawable.mangalsutr_1,
////			R.drawable.river_0,
////			R.drawable.marriage_6,
////			R.drawable.marriage_7,
////			R.drawable.swan_1,
////			R.drawable.marriage_0,
////			R.drawable.marriage_13,
////			R.drawable.sea_romance_3,
////			R.drawable.mango_2,
////			R.drawable.moon_3,
////			R.drawable.krishna_2,
////			R.drawable.marriage_12,
////			R.drawable.moon_0,
////			R.drawable.marriage_10,
////			R.drawable.entry_7,
////			R.drawable.sea_romance_1,
////			R.drawable.sanai,
////			R.drawable.mangalsutr_2,
////			R.drawable.hand_hand_1,
////			R.drawable.moon_1,
////			R.drawable.parijat,
////			R.drawable.krishna_4,
////			R.drawable.lunch_2,
////			R.drawable.mangalsutr_0,
////			R.drawable.sun_0,
////			R.drawable.ring_0,
////			R.drawable.lunch_2,
////			R.drawable.kalash,
////			R.drawable.marriage_12,
////			R.drawable.fire_1,
////			R.drawable.entry_2,
////			R.drawable.ring_1,
////			R.drawable.ganesh_,
////			R.drawable.varmala,
////			R.drawable.marriage_12,
////			R.drawable.rain_1,
////			R.drawable.marriage_14,
////			R.drawable.marriage_9,
////			R.drawable.entry_5,
////			R.drawable.ram_2,
////			R.drawable.antarpath,
////			R.drawable.aboli_1,
////			R.drawable.rangoli_0,
////			R.drawable.marriage_9,
////			R.drawable.marriage_5,
////			R.drawable.namskar_1,
////			R.drawable.kali_3,
////			R.drawable.bride_2,
////			R.drawable.moon_2,
////			R.drawable.shreekhand_1,
//
//		},
//		{
////			R.drawable.sea_romance_4,
////			R.drawable.jwel_4,
////			R.drawable.rain_0,
////			R.drawable.ganesh_6,
////			R.drawable.tabla_0,
////			R.drawable.moon_0,
////			R.drawable.swan_0,
////			R.drawable.building,
////			R.drawable.eye_0,
////			R.drawable.mehandi_0,
////			R.drawable.vari_2,
////			R.drawable.ratrani_1,
////			R.drawable.varmala,
////			R.drawable.namskar_0,
////			R.drawable.child_1,
////			R.drawable.rain_0,
////			R.drawable.sea_romance_1,
////			R.drawable.funny_4,
////			R.drawable.kali_0,
////			R.drawable.ring_2,
////			R.drawable.river_0,
////			R.drawable.sugar_0,
////			R.drawable.wheat_1,
////			R.drawable.temple_0,
////			R.drawable.sea_romance_2,
////			R.drawable.hand_hand,
////			R.drawable.sun_1,
////			R.drawable.bride_0,
////			R.drawable.sugar_1,
////			R.drawable.milk_0,
////			R.drawable.puran_0,
////			R.drawable.sea_romance_2,
////			R.drawable.grape_0,
////			R.drawable.entry_1,
////			R.drawable.rain_0,
////			R.drawable.rose_1,
////			R.drawable.chandan,
////			R.drawable.social,
////			R.drawable.river_1,
////			R.drawable.river_0,
////			R.drawable.thushi_1,
////			R.drawable.krishna_1,
////			R.drawable.laxmi_puja,
////			R.drawable.coin_1,
////			R.drawable.green_sadi,
////			R.drawable.rose_3,
////			R.drawable.krishna_0,
////			R.drawable.marriage_4,
////			R.drawable.mehandi_0,
////			R.drawable.seasoar_0,
////			R.drawable.shivaji_1,
////			R.drawable.lunch_1,
////			R.drawable.ram_1,
////			R.drawable.feta,
////			R.drawable.rainbow_1,
////			R.drawable.seasoar_2,
////			R.drawable.bride_0,
////			R.drawable.haldi_kunku_0,
////			R.drawable.river_2,
////			R.drawable.wool_0,
////			R.drawable.diya_0,
////			R.drawable.krishna_1,
////			R.drawable.ganesh_3,
////			R.drawable.leaf,
////			R.drawable.jwel_1,
////			R.drawable.jwel_4,
////			R.drawable.fulvat,
////			R.drawable.rainbow_1,
////			R.drawable.krishna_0,
////			R.drawable.sun_2,
////			R.drawable.tulas_0,
////			R.drawable.sun_0,
////			R.drawable.book,
////			R.drawable.parijat,
////			R.drawable.jwel_5,
////			R.drawable.chandan,
////			R.drawable.wool_1,
////			R.drawable.namskar_1,
////			R.drawable.krishna_6,
////			R.drawable.hand_hand_2,
////			R.drawable.rose_1,
////			R.drawable.parrot,
////			R.drawable.ratrani_0,
////			R.drawable.fulvat,
////			R.drawable.murti,
//
//		},
//		{
////			R.drawable.sea_romance_3,
////			R.drawable.pawdar,
////			R.drawable.ajintha_1,
////			R.drawable.cow,
////			R.drawable.drink_1,
////			R.drawable.dryfruit_0,
////			R.drawable.puran_1,
////			R.drawable.jwel_3,
////			R.drawable.handa_0,
////			R.drawable.tulas_0,
////			R.drawable.america,
////			R.drawable.wheat_0,
////			R.drawable.windows,
////			R.drawable.ganesh_6,
////			R.drawable.funny_11,
////			R.drawable.bread_butter_2,
////			R.drawable.monkey_0,
////			R.drawable.bush,
////			R.drawable.bat,
////			R.drawable.bread_butter_0,
////			R.drawable.crow_sparrow,
////			R.drawable.temple_0,
////			R.drawable.kali_3,
////			R.drawable.tulas_1,
////			R.drawable.sea_romance_3,
////			R.drawable.mango_0,
////			R.drawable.taj_1,
////			R.drawable.krishna_5,
////			R.drawable.money_2,
////			R.drawable.grape_1,
////			R.drawable.money_0,
////			R.drawable.curd,
////			R.drawable.bread_butter_4,
////			R.drawable.key,
////			R.drawable.water_0,
////			R.drawable.car,
////			R.drawable.math,
////			R.drawable.kamal_1,
////			R.drawable.namskar_0,
////			R.drawable.plain,
////			R.drawable.masala_1,
////			R.drawable.rose_1,
////			R.drawable.funny_0,
////			R.drawable.funny_16,
//
//		},
//		{
////			R.drawable.puja_2,
////			R.drawable.swan_2,
////			R.drawable.puja_6,
////			R.drawable.book,
////			R.drawable.haldi_kunku_0,
////			R.drawable.namskar_1,
////			R.drawable.fire_1,
////			R.drawable.puja_1,
////			R.drawable.puja_3,
////			R.drawable.swan_0,
////			R.drawable.tabla_0,
////			R.drawable.ram_2,
////			R.drawable.laxmi_puja,
////			R.drawable.laxmi_1,
////			R.drawable.green_bangle_0,
////			R.drawable.grape_2,
////			R.drawable.diya_1,
//
//		},
//		{
////			R.drawable.green_bangle_4,
////			R.drawable.mangalagaur_2,
////			R.drawable.mangalagaur_4,
////			R.drawable.mangalagaur_5,
////			R.drawable.mangalagaur_6,
////			R.drawable.mangalagaur_3,
////			R.drawable.mangalagaur_0,
////			R.drawable.marriage_10,
//
//		},
//		{
////			R.drawable.sun_4,
////			R.drawable.child_9,
////			R.drawable.dohale_3,
////			R.drawable.dohale_2,
////			R.drawable.child_10,
////			R.drawable.dohale_0,
////			R.drawable.child_8,
////			R.drawable.child_11,
////			R.drawable.puja_8,
////			R.drawable.money_1,
//
//		},
//		{
////			R.drawable.child_2,
////			R.drawable.child_3,
////			R.drawable.child_4,
////			R.drawable.child_5,
////			R.drawable.child_6,
////			R.drawable.child_7,
////			R.drawable.diya_1,
//
//		},
//		{
////			R.drawable.ganesh_0,
////			R.drawable.namskar_1,
////			R.drawable.rose_0,
////			R.drawable.rain_1,
////			R.drawable.marriage_4,
////			R.drawable.marriage_11,
//
//		},
//		{
////			R.drawable.entry_5,
////			R.drawable.entry_7,
////			R.drawable.entry_4,
////			R.drawable.diya_0,
////			R.drawable.entry_3,
////			R.drawable.namskar_0,
////			R.drawable.ganesh_5,
////			R.drawable.bride_3,
////			R.drawable.home_0,
//
//		},
//		{
////			R.drawable.rakshabandhan,
////			R.drawable.moon_2,
////			R.drawable.diya_0,
////			R.drawable.f_252,
////			R.drawable.haldi_kunku_0,
////			R.drawable.laxmi_ganapati,
////			R.drawable.laxmi_puja,
//
//		},
//	};
//	
//	public static final int [][] categoryDetailImageUser1= {
//		{
////			R.drawable.hand_hand_2,
////			R.drawable.marriage_0,
////			R.drawable.ram_0,
////			R.drawable.jwel_4,
////			R.drawable.rose_3,
////			R.drawable.antarpath,
////			R.drawable.lunch_3,
////			R.drawable.garland_0,
////			R.drawable.krishna_4,
////			R.drawable.moon_2,
////			R.drawable.mangalsutr_4,
////			R.drawable.fire_1,
////			R.drawable.bride_1,
////			R.drawable.heart,
////			R.drawable.child_1,
////			R.drawable.grape_1,
////			R.drawable.kali_3,
////			R.drawable.marriage_9,
////			R.drawable.rain_1,
////			R.drawable.marriage_14,
////			R.drawable.marriage_12,
////			R.drawable.varmala,
////			R.drawable.lunch_2,
////			R.drawable.hand_hand_1,
////			R.drawable.sea_romance_1,
////			R.drawable.marriage_10,
////			R.drawable.moon_2,
////			R.drawable.marriage_14,
////			R.drawable.krishna_2,
////			R.drawable.moon_3,
////			R.drawable.mango_2,
////			R.drawable.sea_romance_3,
////			R.drawable.marriage_13,
////			R.drawable.river_0,
////			R.drawable.lunch_0,
////			R.drawable.marriage_0,
////			R.drawable.marriage_13,
////			R.drawable.marriage_7,
////			R.drawable.ganesh_,
////			R.drawable.lunch_2,
////			R.drawable.shreekhand_1,
////			R.drawable.marriage_12,
////			R.drawable.rangoli_0,
////			R.drawable.sea_romance_4,
////			R.drawable.shankar,
////			R.drawable.bride_1,
////			R.drawable.shreekhand_1,
////			R.drawable.ganesh_4,
////			R.drawable.sea_romance_3,
////			R.drawable.diya_0,
//	
//		},
//		{
////			R.drawable.sun_2,
////			R.drawable.sugar_0,
////			R.drawable.swan_2,
////			R.drawable.rose_0,
////			R.drawable.building,
////			R.drawable.rangoli_2,
////			R.drawable.ganesh_2,
////			R.drawable.parrot,
////			R.drawable.leaf,
////			R.drawable.krishna_0,
////			R.drawable.grape_0,
////			R.drawable.rain_1,
////			R.drawable.varmala,
////			R.drawable.funny_12,
////			R.drawable.namskar_0,
////			R.drawable.rain_0,
////			R.drawable.sea_romance_4,
////			R.drawable.sea_romance_1,
////			R.drawable.funny_4,
////			R.drawable.bride_2,
////			R.drawable.sun_4,
////			R.drawable.kali_2,
////			R.drawable.kali_0,
////			R.drawable.shankar,
////			R.drawable.swan_2,
////			R.drawable.river_0,
////			R.drawable.sugar_1,
////			R.drawable.bride_0,
////			R.drawable.kokil_0,
////			R.drawable.kali_3,
////			R.drawable.funny_9,
////			R.drawable.wheat_1,
////			R.drawable.sea_romance_2,
////			R.drawable.hand_hand,
////			R.drawable.milk_0,
////			R.drawable.coin_1,
////			R.drawable.rain_0,
////			R.drawable.ram_1,
////			R.drawable.feta,
////			R.drawable.rainbow_1,
////			R.drawable.seasoar_2,
////			R.drawable.diya_0,
////			R.drawable.krishna_1,
////			R.drawable.leaf,
////			R.drawable.jwel_1,
////			R.drawable.jwel_4,
////			R.drawable.fulvat,
////			R.drawable.krishna_0,
////			R.drawable.tulas_0,
////			R.drawable.sun_0,
////			R.drawable.book,
////			R.drawable.chandan,
////			R.drawable.wool_1,
////			R.drawable.rose_1,
////			R.drawable.parrot,
//
//		},
//		{
////			R.drawable.monkey_0,
////			R.drawable.wheat_0,
////			R.drawable.shreekhand_0,
////			R.drawable.tulas_1,
////			R.drawable.mango_0,
////			R.drawable.money_0,
////			R.drawable.funny_13,
////			R.drawable.bread_butter_2,
////			R.drawable.funny_16,
////			R.drawable.funny_2,
////			R.drawable.funny_12,
////			R.drawable.bread_butter_0,
////			R.drawable.crow_sparrow,
////			R.drawable.temple_0,
////			R.drawable.sea_romance_3,
////			R.drawable.taj_1,
////			R.drawable.money_2,
////			R.drawable.curd,
////			R.drawable.funny_15,
////			R.drawable.plain,
////			R.drawable.handa_1,
////			R.drawable.masala_1,
////			R.drawable.puran_1,
////			R.drawable.dryfruit_1,
////			R.drawable.pawdar,
////			R.drawable.cow,
////			R.drawable.kamal_1,
////			R.drawable.funny_0,
////			R.drawable.math,
////			R.drawable.bread_butter_4,
//
//		},
//		{
////			R.drawable.puja_pat,
////			R.drawable.tabla_1,
////			R.drawable.smoke_1,
////			R.drawable.puja_4,
////			R.drawable.diya_0,
////			R.drawable.fire_1,
////			R.drawable.ratrani_1,
////			R.drawable.puja_6,
////			R.drawable.ram_2,
//
//		},
//	};
	
	public static final int categoryStartId_Mail = R.string.f_cat_1;
	public static final int categoryEndId_Mail = R.string.f_cat_10;
	
	public static final int categoryStartId_Femail = R.string.m_cat_1;
	public static final int categoryEndId_Femail = R.string.m_cat_4;
	
	
//	[category][fe]
	public static final int [][] categoryMessageStartId= {
		{R.string.f_cat_1_ms1,R.string.m_cat_1_ms1},
		{R.string.f_cat_2_ms1,R.string.m_cat_2_ms1},
		{R.string.f_cat_3_ms1,R.string.m_cat_3_ms1},
		{R.string.f_cat_4_ms1,R.string.m_cat_4_ms1},
		{R.string.f_cat_5_ms1,R.string.m_cat_5_ms1},
		{R.string.f_cat_6_ms1,R.string.m_cat_6_ms1},
		{R.string.f_cat_7_ms1,R.string.m_cat_7_ms1},
		{R.string.f_cat_8_ms1,R.string.m_cat_8_ms1},
		{R.string.f_cat_9_ms1,R.string.m_cat_9_ms1},
		{R.string.f_cat_10_ms1,R.string.m_cat_10_ms1},
	};
	public static final int [][] categoryMessageEndId= {
		{R.string.f_cat_1_ms103,R.string.m_cat_1_ms50},
			{R.string.f_cat_2_ms85,R.string.m_cat_2_ms55},
			{R.string.f_cat_3_ms44,R.string.m_cat_3_ms30},
			{R.string.f_cat_4_ms17,R.string.m_cat_4_ms9},
			{R.string.f_cat_5_ms8,R.string.m_cat_5_ms3},
			{R.string.f_cat_6_ms10,R.string.m_cat_6_ms8},
			{R.string.f_cat_7_ms7,R.string.m_cat_7_ms8},
			{R.string.f_cat_8_ms6,R.string.m_cat_8_ms8},
			{R.string.f_cat_9_ms9,R.string.m_cat_9_ms8},
			{R.string.f_cat_10_ms7,R.string.m_cat_10_ms8},
	};
	
	public static final int [][] categoryMessageDeailStartId= {
		{R.string.f_cat_1_ms1_Detail,R.string.m_cat_1_ms1_Detail},
		{R.string.f_cat_2_ms1_Detail,R.string.m_cat_2_ms1_Detail},
		{R.string.f_cat_3_ms1_Detail,R.string.m_cat_3_ms1_Detail},
		{R.string.f_cat_4_ms1_Detail,R.string.m_cat_4_ms1_Detail},
		{R.string.f_cat_5_ms1_Detail,R.string.m_cat_5_ms1_Detail},
		{R.string.f_cat_6_ms1_Detail,R.string.m_cat_6_ms1_Detail},
		{R.string.f_cat_7_ms1_Detail,R.string.m_cat_7_ms1_Detail},
		{R.string.f_cat_8_ms1_Detail,R.string.m_cat_8_ms1_Detail},
		{R.string.f_cat_9_ms1_Detail,R.string.m_cat_9_ms1_Detail},
		{R.string.f_cat_10_ms1_Detail,R.string.m_cat_10_ms1_Detail},
	};
	public static final int [][] categoryMessageDeailEndId= {
		{R.string.f_cat_1_ms103_Detail,R.string.m_cat_1_ms50_Detail},
		{R.string.f_cat_2_ms85_Detail,R.string.m_cat_2_ms55_Detail},
		{R.string.f_cat_3_ms44_Detail,R.string.m_cat_3_ms30_Detail},
		{R.string.f_cat_4_ms17_Detail,R.string.m_cat_4_ms9_Detail},
		{R.string.f_cat_5_ms8_Detail,R.string.m_cat_5_ms3_Detail},
		{R.string.f_cat_6_ms10_Detail,R.string.m_cat_6_ms10_Detail},
		{R.string.f_cat_7_ms7_Detail,R.string.m_cat_7_ms10_Detail},
		{R.string.f_cat_8_ms6_Detail,R.string.m_cat_8_ms10_Detail},
		{R.string.f_cat_9_ms9_Detail,R.string.m_cat_9_ms10_Detail},
		{R.string.f_cat_10_ms7_Detail,R.string.m_cat_10_ms10_Detail},
	};

	
	
	
//	public static final int [][] conflictMsgId= {
//		{R.string.m_cat_1_ms1_Detail,R.string.f_cat_1_ms1_Detail},
//		{R.string.m_cat_1_ms2_Detail,R.string.f_cat_1_ms2_Detail},
//		{R.string.m_cat_1_ms3_Detail,R.string.f_cat_1_ms3_Detail},
//		{R.string.m_cat_1_ms4_Detail,R.string.f_cat_1_ms4_Detail},
//		{R.string.m_cat_1_ms5_Detail,R.string.f_cat_1_ms5_Detail},
//		{R.string.m_cat_1_ms6_Detail,R.string.f_cat_1_ms6_Detail},
//		{R.string.m_cat_1_ms7_Detail,R.string.f_cat_1_ms7_Detail},
//		{R.string.m_cat_1_ms8_Detail,R.string.f_cat_1_ms8_Detail},
//		{R.string.m_cat_1_ms9_Detail,R.string.f_cat_1_ms9_Detail},
//		{R.string.m_cat_1_ms10_Detail,R.string.f_cat_1_ms10_Detail},
//		{R.string.m_cat_1_ms11_Detail,R.string.f_cat_1_ms11_Detail},
//		{R.string.m_cat_1_ms12_Detail,R.string.f_cat_1_ms12_Detail},
//		
//		{R.string.m_cat_2_ms1_Detail,R.string.f_cat_2_ms1_Detail},
//		{R.string.m_cat_2_ms2_Detail,R.string.f_cat_2_ms2_Detail},
//		{R.string.m_cat_2_ms3_Detail,R.string.f_cat_2_ms3_Detail},
//		{R.string.m_cat_2_ms4_Detail,R.string.f_cat_2_ms4_Detail},
//		{R.string.m_cat_2_ms5_Detail,R.string.f_cat_2_ms5_Detail},
//		{R.string.m_cat_2_ms6_Detail,R.string.f_cat_2_ms6_Detail},
//		{R.string.m_cat_2_ms7_Detail,R.string.f_cat_2_ms7_Detail},
//		{R.string.m_cat_2_ms8_Detail,R.string.f_cat_2_ms8_Detail},
//		{R.string.m_cat_2_ms9_Detail,R.string.f_cat_2_ms9_Detail},
//		{R.string.m_cat_2_ms10_Detail,R.string.f_cat_2_ms10_Detail},
//		{R.string.m_cat_2_ms11_Detail,R.string.f_cat_2_ms11_Detail},
//		{R.string.m_cat_2_ms12_Detail,R.string.f_cat_2_ms12_Detail},
//		{R.string.m_cat_2_ms13_Detail,R.string.f_cat_2_ms13_Detail},
//		
//		{R.string.m_cat_3_ms1_Detail,R.string.f_cat_3_ms1_Detail},
//		{R.string.m_cat_3_ms2_Detail,R.string.f_cat_3_ms2_Detail},
//		{R.string.m_cat_3_ms3_Detail,R.string.f_cat_3_ms3_Detail},
//		{R.string.m_cat_3_ms4_Detail,R.string.f_cat_3_ms4_Detail},
//		{R.string.m_cat_3_ms5_Detail,R.string.f_cat_3_ms5_Detail},
//		
//		
//	};
}
